exports.itemActions = {
  GET_ITEMS: 'GET_ITEMS',
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  LOAD_ITEMS_START: "LOAD_ITEMS_START",
  LOAD_ITEMS_ERROR: "LOAD_ITEMS_ERROR",
  LOAD_ITEMS_SUCCESS: "LOAD_ITEMS_SUCCESS",
  LOAD_ITEM_START: "LOAD_ITEM_START",
  LOAD_ITEM_ERROR: "LOAD_ITEM_ERROR",
  LOAD_ITEM_SUCCESS: "LOAD_ITEM_SUCCESS",
  CREATE_ITEM_START: "CREATE_ITEM_START",
  CREATE_ITEM_ERROR: "CREATE_ITEM_ERROR",
  CREATE_ITEM_SUCCESS: "CREATE_ITEM_SUCCESS"
};

exports.itemTypes = {
  ANIME: "ANIME",
  MOVIE: "MOVIE",
  BOOK: "BOOK"
}

exports.authActions = {
  START_LOGIN: "START_LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  START_SIGNUP: "START_SIGNUP",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_ERROR: "SIGNUP_ERROR"
}